
COMMA = 1
TAB = 2
COMMA_TEXT = ','
TAB_TEXT = 'TAB'

SEPARATOR_CHOICES = (
    (COMMA, COMMA_TEXT),
    (TAB, TAB_TEXT),
)

DOUBLE_QUOTE = 1
VERTICAL_BAR = 2
DQ_TEXT = '"'
VB_TEXT = '|'

QUOTE_CHOICES = (
    (DOUBLE_QUOTE, DQ_TEXT),
    (VERTICAL_BAR, VB_TEXT),
)


PENDING_STATUS = 1
PROCESSING_STATUS = 2
READY_STATUS = 3

STATUS_CHOICES = (
    (PENDING_STATUS, 'Pending'),
    (PROCESSING_STATUS, 'Processing'),
    (READY_STATUS, 'Ready'),
)

delimiters = {COMMA: COMMA_TEXT, TAB: '\t'}
quotes = {DOUBLE_QUOTE: DQ_TEXT, VERTICAL_BAR: VB_TEXT}
